"""
AI WealthPilot - AI Wealth Advisor Agent
AI WealthPilot - AI 财富顾问 Agent

The AI Advisor Agent is the intelligent decision-support core of the system.
It consumes a complete ClientProfile (generated by the profiler module) and
leverages a Large Language Model (DeepSeek V4 Pro) to produce a personalized,
CFA-compliant investment advisory report.

AI 顾问 Agent 是系统的智能决策支持核心。
它消费一个完整的 ClientProfile（由 profiler 模块生成），
并利用大语言模型（DeepSeek V4 Pro）生成个性化的、
符合 CFA 规范的投资咨询建议书。

Architecture / 架构:
    ClientProfile (profiler.py)
            ↓
    _build_system_prompt()   ← CFA knowledge-constrained system prompt
    _build_user_prompt()     ← Serialize ClientProfile into structured context
            ↓
    DeepSeek V4 Pro API      ← OpenAI-compatible SDK, base_url=deepseek
            ↓
    AdvisorReport            ← Structured advisory report output

CFA Reference / CFA 参考:
    - CFA L3 Private Wealth Management: Investment Policy Statement (IPS)
      CFA 三级私人财富管理：投资政策声明
    - CFA L3: Behavioral Finance — common investor biases
      CFA 三级：行为金融学 —— 常见投资者偏差
    - CFA L3: Asset Allocation — strategic vs tactical
      CFA 三级：资产配置 —— 战略性 vs 战术性
    - CFA L3: Portfolio Construction — diversification, risk budgeting
      CFA 三级：组合构建 —— 分散化、风险预算

Model / 模型:
    DeepSeek V4 Pro (deepseek-v4-pro)
    API compatible with OpenAI Python SDK
    Base URL: https://api.deepseek.com
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Generator, Optional

from openai import OpenAI

from src.config import (
    DEEPSEEK_API_KEY,
    DEEPSEEK_BASE_URL,
    DEEPSEEK_MODEL,
    DEEPSEEK_MAX_TOKENS,
    DEEPSEEK_TEMPERATURE,
)
from src.agents.profiler import ClientProfile

# 日志配置 / Logger configuration
logger = logging.getLogger(__name__)


# ============================================================
# Data Model — Advisory Report
# 数据模型 —— 建议书
# ============================================================

@dataclass
class AdvisorReport:
    """
    Structured output of the AI Advisor Agent.
    AI 顾问 Agent 的结构化输出。

    Contains the full advisory report text along with metadata
    such as the model used, generation timestamp, and token usage.

    包含完整的建议书文本以及元数据，
    如使用的模型、生成时间戳和 token 用量。
    """
    # 建议书正文（Markdown 格式）/ Report body (Markdown format)
    content: str = ""
    # 使用的模型 / Model used
    model: str = ""
    # 生成时间 / Generation timestamp
    generated_at: str = ""
    # Token 用量 / Token usage
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    # 客户名称（用于关联）/ Client name (for association)
    client_name: str = ""
    # 生成是否成功 / Whether generation succeeded
    success: bool = False
    # 错误信息（如有）/ Error message (if any)
    error_message: str = ""


# ============================================================
# System Prompt — CFA-Aligned Financial Advisor
# 系统提示词 —— CFA 对标财务顾问
# ============================================================

# CFA 知识框架约束的 System Prompt
# 设计原则：角色扮演 + 知识约束 + 输出格式规范
# Design principles: role-play + knowledge constraints + output format spec
SYSTEM_PROMPT = """You are a Private Wealth Management advisor trained on the CFA® Level III curriculum, specializing in the Private Wealth Management (PWM) pathway. You operate within the CFA Institute's professional standards and ethical guidelines.

你是一位基于 CFA® 三级知识体系训练的私人财富管理顾问，专精于私人财富管理（PWM）方向。你遵循 CFA 协会的专业标准和道德准则。

## Your Core Competencies / 核心能力

1. **Investment Policy Statement (IPS) Framework / 投资政策声明框架**
   - Return objectives (收益目标)
   - Risk tolerance: Ability & Willingness assessment (风险承受能力：承受能力与承担意愿评估)
   - Time horizon analysis (投资期限分析)
   - Liquidity needs (流动性需求)
   - Tax considerations (税务考量)
   - Legal & regulatory constraints (法律与监管约束)
   - Unique circumstances (特殊情况)

2. **Asset Allocation / 资产配置**
   - Strategic Asset Allocation (SAA) (战略性资产配置)
   - Mean-Variance Optimization principles (均值-方差优化原理)
   - Risk budgeting and diversification (风险预算与分散化)
   - Human capital considerations (人力资本考量)

3. **Behavioral Finance / 行为金融学**
   - Identify common biases (loss aversion, overconfidence, anchoring)
   - 识别常见偏差（损失厌恶、过度自信、锚定效应）
   - Provide debiasing recommendations (提供纠偏建议)

## Output Requirements / 输出要求

Generate your advisory report in **bilingual format (English & Chinese / 中英双语)** with the following 6 sections. Use Markdown formatting:

1. **📋 Client Summary / 客户概况总结**
   - Summarize the client's profile, financial situation, and key characteristics
   - 总结客户画像、财务状况和关键特征

2. **🎯 Investment Objectives Analysis / 投资目标分析**
   - Analyze each goal's feasibility, required return, and priority
   - 分析每个目标的可行性、所需收益率和优先级

3. **⚖️ Risk Tolerance Interpretation / 风险承受能力解读**
   - Interpret the ability vs willingness scores
   - If they conflict, explain the CFA "use the lower" principle
   - 解读承受能力与承担意愿评分
   - 如果两者冲突，解释 CFA "就低不就高"原则

4. **📊 Recommended Asset Allocation / 建议资产配置方案**
   - Provide a specific allocation with percentages
   - Explain the rationale using MPT principles
   - Include asset classes: equities, bonds, alternatives, cash
   - 提供具体的配置百分比
   - 用 MPT 原理解释配置理由
   - 包含资产类别：股票、债券、另类投资、现金

5. **💡 Implementation Strategy / 实施策略与注意事项**
   - Specific ETF/fund suggestions aligned with allocation
   - Rebalancing frequency recommendation
   - Tax-efficient strategies if applicable
   - 与配置对应的具体 ETF/基金建议
   - 再平衡频率建议
   - 如适用，提供税务高效策略

6. **⚠️ Risk Disclosure / 风险披露与免责声明**
   - Past performance ≠ future results
   - Model limitations and assumptions
   - Recommendation to consult a licensed advisor
   - 历史表现不代表未来收益
   - 模型局限性和假设
   - 建议咨询持牌顾问

## Constraints / 约束

- Be professional, thorough, and data-driven
- Always cite CFA principles when making recommendations
- Never guarantee specific returns or outcomes
- Consider the client's complete financial picture holistically
- Adapt tone to the client's investment knowledge level
- 专业、全面、以数据为驱动
- 提出建议时始终引用 CFA 原则
- 绝不保证具体收益或结果
- 全面考虑客户的整体财务状况
- 根据客户的投资知识水平调整措辞"""


# ============================================================
# Prompt Construction — Serialize ClientProfile
# 提示词构建 —— 序列化客户画像
# ============================================================

def _build_user_prompt(profile: ClientProfile) -> str:
    """
    Serialize a ClientProfile into a structured text prompt for the LLM.
    将 ClientProfile 序列化为结构化文本提示词供 LLM 消费。

    The prompt presents all IPS-relevant data in a clear, parseable format
    so the model can produce an accurate, personalized advisory report.

    提示词以清晰、可解析的格式呈现所有 IPS 相关数据，
    使模型能够生成准确的个性化建议书。

    Args:
        profile: Complete ClientProfile instance with risk assessment.
                 包含风险评估的完整 ClientProfile 实例。

    Returns:
        Formatted user prompt string.
        格式化的用户提示词字符串。
    """
    # 构建投资目标列表 / Build investment goals list
    goals_text = ""
    if profile.goals:
        for i, goal in enumerate(profile.goals, 1):
            goals_text += (
                f"  {i}. {goal.name}\n"
                f"     - Target Amount / 目标金额: ${goal.target_amount:,.0f}\n"
                f"     - Time Horizon / 时间范围: {goal.years} years / 年\n"
                f"     - Priority / 优先级: {goal.priority}\n"
            )
    else:
        goals_text = "  No specific goals defined / 未定义具体目标\n"

    # 构建特殊情况文本 / Build unique circumstances text
    unique_text_parts = []
    if profile.esg_preference:
        unique_text_parts.append("- ESG investing preference / 偏好 ESG 投资")
    if profile.sector_restrictions:
        restrictions = ", ".join(profile.sector_restrictions)
        unique_text_parts.append(
            f"- Sector restrictions / 行业限制: {restrictions}"
        )
    if profile.notes:
        unique_text_parts.append(f"- Additional notes / 备注: {profile.notes}")
    unique_text = "\n".join(unique_text_parts) if unique_text_parts else "  None / 无"

    # 风险评分冲突检测 / Detect risk score conflict
    rp = profile.risk_profile
    conflict_note = ""
    if rp.ability_score > 0 and rp.willingness_score > 0:
        if abs(rp.ability_score - rp.willingness_score) >= 1.0:
            conflict_note = (
                f"\n  ⚠️ CONFLICT DETECTED / 冲突检测: "
                f"Ability ({rp.ability_score:.1f}) vs "
                f"Willingness ({rp.willingness_score:.1f}) differ by "
                f"{abs(rp.ability_score - rp.willingness_score):.1f} points. "
                f"CFA principle: use the LOWER score."
            )

    # 组装完整提示词 / Assemble complete prompt
    prompt = f"""Please generate a comprehensive investment advisory report for the following client:
请为以下客户生成全面的投资咨询建议书：

═══════════════════════════════════════════
CLIENT PROFILE / 客户画像
═══════════════════════════════════════════

【Basic Information / 基本信息】
  Name / 姓名: {profile.name}
  Age / 年龄: {profile.age}
  Marital Status / 婚姻状况: {profile.marital_status}
  Dependents / 受抚养人数: {profile.dependents}

【Financial Situation / 财务状况】
  Annual Income / 年收入: ${profile.financial.annual_income:,.0f}
  Annual Expenses / 年支出: ${profile.financial.annual_expenses:,.0f}
  Investable Assets / 可投资资产: ${profile.financial.investable_assets:,.0f}
  Total Liabilities / 负债总额: ${profile.financial.total_liabilities:,.0f}
  Net Worth / 净资产: ${profile.financial.net_worth:,.0f}
  Savings Rate / 储蓄率: {profile.financial.savings_rate:.1%}
  Debt-to-Asset Ratio / 资产负债率: {profile.financial.debt_to_asset_ratio:.1%}
  Emergency Fund / 应急基金: {profile.financial.emergency_fund_months:.0f} months / 月

【Investment Goals / 投资目标】
{goals_text}
【Time Horizon / 投资期限】
  Primary Horizon / 主要期限: {profile.time_horizon_years} years / 年
  Multi-stage / 多阶段: {"Yes / 是" if profile.is_multi_stage else "No / 否"}

【Risk Tolerance Assessment / 风险承受能力评估】
  Ability Score / 承受能力评分: {rp.ability_score:.1f} / 5.0
  Willingness Score / 承担意愿评分: {rp.willingness_score:.1f} / 5.0
  Final Score / 最终评分: {rp.final_score:.1f} / 5.0 (= min(Ability, Willingness))
  Risk Level / 风险等级: {rp.tolerance_level}{conflict_note}

【Tax Status / 税务状况】
  {profile.tax_status}

【Liquidity Needs / 流动性需求】
  ${profile.liquidity_needs:,.0f}

【Unique Circumstances / 特殊情况】
{unique_text}

═══════════════════════════════════════════

Please generate the advisory report following the 6-section format specified in your instructions.
请按照你指令中规定的 6 个章节格式生成建议书。"""

    return prompt


# ============================================================
# API Client — DeepSeek V4 Pro via OpenAI SDK
# API 客户端 —— 通过 OpenAI SDK 调用 DeepSeek V4 Pro
# ============================================================

def _get_client() -> OpenAI:
    """
    Initialize and return an OpenAI-compatible client for DeepSeek.
    初始化并返回一个兼容 OpenAI 的 DeepSeek 客户端。

    DeepSeek's API is fully compatible with the OpenAI Python SDK.
    We only need to override the base_url and api_key.

    DeepSeek 的 API 完全兼容 OpenAI Python SDK。
    只需要覆盖 base_url 和 api_key。

    Returns:
        Configured OpenAI client instance.

    Raises:
        ValueError: If DEEPSEEK_API_KEY is not configured.
    """
    if not DEEPSEEK_API_KEY:
        raise ValueError(
            "DEEPSEEK_API_KEY is not configured. "
            "Please set it in your .env file. "
            "DeepSeek API Key 未配置，请在 .env 文件中设置。"
        )

    return OpenAI(
        api_key=DEEPSEEK_API_KEY,
        base_url=DEEPSEEK_BASE_URL,
    )


def is_api_configured() -> bool:
    """
    Check if the DeepSeek API key is configured.
    检查 DeepSeek API Key 是否已配置。

    Returns:
        True if DEEPSEEK_API_KEY is set and non-empty.
        如果 DEEPSEEK_API_KEY 已设置且非空，返回 True。
    """
    return bool(DEEPSEEK_API_KEY)


# ============================================================
# Shared Helpers — Reduce Duplication Across API Functions
# 共享辅助函数 —— 减少 API 函数之间的重复
# ============================================================

def _create_initial_report(profile: ClientProfile) -> AdvisorReport:
    """
    Create an initial AdvisorReport with metadata pre-filled.
    创建一个预填充元数据的初始 AdvisorReport。

    Args:
        profile: ClientProfile instance.

    Returns:
        AdvisorReport with client_name, model, and timestamp set.
    """
    return AdvisorReport(
        client_name=profile.name,
        model=DEEPSEEK_MODEL,
        generated_at=datetime.now().isoformat(),
    )


def _build_messages(profile: ClientProfile) -> list[dict]:
    """
    Build the message list for the DeepSeek API call.
    构建 DeepSeek API 调用的消息列表。

    Args:
        profile: ClientProfile instance.

    Returns:
        List of message dicts with system and user roles.
    """
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": _build_user_prompt(profile)},
    ]


# ============================================================
# Core Generation Functions
# 核心生成函数
# ============================================================

def generate_advice(profile: ClientProfile) -> AdvisorReport:
    """
    Generate a complete investment advisory report for a client.
    为客户生成完整的投资咨询建议书。

    This is the main entry point for non-streaming report generation.
    It sends the full ClientProfile to DeepSeek V4 Pro and returns
    a structured AdvisorReport with the complete response.

    这是非流式报告生成的主入口。
    它将完整的 ClientProfile 发送到 DeepSeek V4 Pro，
    并返回包含完整响应的结构化 AdvisorReport。

    Args:
        profile: Complete ClientProfile instance with risk assessment.
                 包含风险评估的完整 ClientProfile 实例。

    Returns:
        AdvisorReport with the generated advisory content.
        包含生成的建议内容的 AdvisorReport。
    """
    report = _create_initial_report(profile)

    try:
        client = _get_client()

        messages = _build_messages(profile)

        logger.info(
            f"Generating advisory report for client: {profile.name} "
            f"using model: {DEEPSEEK_MODEL}"
        )

        # 调用 DeepSeek V4 Pro API（非流式）
        # Call DeepSeek V4 Pro API (non-streaming)
        response = client.chat.completions.create(
            model=DEEPSEEK_MODEL,
            messages=messages,
            max_tokens=DEEPSEEK_MAX_TOKENS,
            temperature=DEEPSEEK_TEMPERATURE,
            stream=False,
        )

        # 提取响应内容 / Extract response content
        report.content = response.choices[0].message.content or ""
        report.success = True

        # 记录 token 用量 / Record token usage
        if response.usage:
            report.prompt_tokens = response.usage.prompt_tokens
            report.completion_tokens = response.usage.completion_tokens
            report.total_tokens = response.usage.total_tokens

        logger.info(
            f"Report generated successfully. "
            f"Tokens: {report.total_tokens} "
            f"(prompt: {report.prompt_tokens}, "
            f"completion: {report.completion_tokens})"
        )

    except ValueError as e:
        # API Key 未配置 / API Key not configured
        report.error_message = str(e)
        logger.error(f"Configuration error: {e}")

    except Exception as e:
        # 网络错误、API 限流等 / Network errors, rate limiting, etc.
        report.error_message = (
            f"Failed to generate report: {str(e)} / "
            f"生成报告失败：{str(e)}"
        )
        logger.error(f"API call failed: {e}", exc_info=True)

    return report


def generate_advice_stream(
    profile: ClientProfile,
) -> Generator[str, None, AdvisorReport]:
    """
    Generate an investment advisory report with streaming output.
    以流式输出方式生成投资咨询建议书。

    This generator yields chunks of text as they arrive from the API,
    enabling real-time display in the Streamlit UI. The final return
    value is the complete AdvisorReport with metadata.

    该生成器在 API 返回文本块时逐块 yield，
    实现 Streamlit UI 中的实时显示。最终返回值是
    包含元数据的完整 AdvisorReport。

    Usage / 用法:
        ```python
        gen = generate_advice_stream(profile)
        for chunk in gen:
            st.write(chunk)  # Real-time display
        report = gen.value   # not accessible directly; use wrapper
        ```

    For Streamlit integration, use `stream_advice()` instead.
    对于 Streamlit 集成，请改用 `stream_advice()`。

    Args:
        profile: Complete ClientProfile instance.

    Yields:
        Text chunks as they arrive from the API.
        从 API 到达的文本块。

    Returns:
        Complete AdvisorReport (accessible via generator.value pattern).
    """
    report = _create_initial_report(profile)

    try:
        client = _get_client()

        messages = _build_messages(profile)

        logger.info(
            f"Starting streaming advisory report for: {profile.name}"
        )

        # 调用 DeepSeek V4 Pro API（流式）
        # Call DeepSeek V4 Pro API (streaming)
        stream = client.chat.completions.create(
            model=DEEPSEEK_MODEL,
            messages=messages,
            max_tokens=DEEPSEEK_MAX_TOKENS,
            temperature=DEEPSEEK_TEMPERATURE,
            stream=True,
        )

        # 逐块 yield 文本 / Yield text chunks
        full_content = []
        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content:
                text = chunk.choices[0].delta.content
                full_content.append(text)
                yield text

        # 组装完整报告 / Assemble complete report
        report.content = "".join(full_content)
        report.success = True

        logger.info(
            f"Streaming report completed for: {profile.name}"
        )

    except ValueError as e:
        report.error_message = str(e)
        logger.error(f"Configuration error: {e}")

    except Exception as e:
        report.error_message = (
            f"Failed to generate report: {str(e)} / "
            f"生成报告失败：{str(e)}"
        )
        logger.error(f"Streaming API call failed: {e}", exc_info=True)

    return report


def stream_advice(profile: ClientProfile) -> tuple[Generator[str, None, None], list]:
    """
    Wrapper for Streamlit streaming integration.
    Streamlit 流式集成的包装器。

    Returns a generator that yields text chunks and a mutable list
    that will contain the final AdvisorReport after iteration completes.

    返回一个 yield 文本块的生成器和一个可变列表，
    该列表在迭代完成后将包含最终的 AdvisorReport。

    This design works around Python's limitation that generator return
    values are not directly accessible, providing a clean API for
    Streamlit's `st.write_stream()`.

    这种设计绕过了 Python 生成器返回值不可直接访问的限制，
    为 Streamlit 的 `st.write_stream()` 提供了简洁的 API。

    Args:
        profile: Complete ClientProfile instance.

    Returns:
        Tuple of (text_generator, report_container).
        - text_generator: yields text chunks for st.write_stream()
        - report_container: list that receives the AdvisorReport on completion

        (文本生成器, 报告容器) 的元组。
        - text_generator: 为 st.write_stream() yield 文本块
        - report_container: 迭代完成后接收 AdvisorReport 的列表
    """
    report_container = []

    def _stream():
        """Inner generator that delegates to generate_advice_stream."""
        report = yield from generate_advice_stream(profile)
        report_container.append(report)

    return _stream(), report_container
